spring.application.name=announcement-board

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Simple homework setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Helpful during development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
